# Generated by Django 2.2.4 on 2019-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('phrase', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('spec_title', models.CharField(max_length=256)),
                ('spec_href', models.URLField(max_length=256)),
                ('is_heading', models.BooleanField(default=False)),
                ('image', models.ImageField(default='images/icon-dog.png', upload_to='images')),
            ],
        ),
    ]
